# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(400, 151)
        self.formLayout = QtWidgets.QFormLayout(login_form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=login_form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEditUsuario = QtWidgets.QLineEdit(parent=login_form)
        self.lineEditUsuario.setObjectName("lineEditUsuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditUsuario)
        self.label_2 = QtWidgets.QLabel(parent=login_form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEditClave = QtWidgets.QLineEdit(parent=login_form)
        self.lineEditClave.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditClave.setObjectName("lineEditClave")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditClave)
        self.btnIniciarSesion = QtWidgets.QPushButton(parent=login_form)
        self.btnIniciarSesion.setObjectName("btnIniciarSesion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnIniciarSesion)

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Login"))
        self.label.setText(_translate("login_form", "usuario:"))
        self.label_2.setText(_translate("login_form", "clave"))
        self.btnIniciarSesion.setText(_translate("login_form", "Iniciar Sesion"))
